# Change these first
owner: 4fx # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Cloudflare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    port: 53
  - name: upptime
    check: "tcp-ping"
    url: $UPPTIME
    port: $UPPTIMEE

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime**"
  introMessage: **Upptime**
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
